//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfCombiner.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfCombiner.Resources.Language.MainWindowResource", typeof(MainWindowResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Document Format (*.pdf)|*.pdf|All files (*.*)|*.*.
        /// </summary>
        public static string AddFilesFilter {
            get {
                return ResourceManager.GetString("AddFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining not possible.
        /// </summary>
        public static string CannotCombineTitle {
            get {
                return ResourceManager.GetString("CannotCombineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string ColumnFileName {
            get {
                return ResourceManager.GetString("ColumnFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ColumnFileSize {
            get {
                return ResourceManager.GetString("ColumnFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid PDF?.
        /// </summary>
        public static string ColumnValidPdf {
            get {
                return ResourceManager.GetString("ColumnValidPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string CompressionFonts {
            get {
                return ResourceManager.GetString("CompressionFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string CompressionImages {
            get {
                return ResourceManager.GetString("CompressionImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string CompressionPageContents {
            get {
                return ResourceManager.GetString("CompressionPageContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string CompressionResources {
            get {
                return ResourceManager.GetString("CompressionResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression:.
        /// </summary>
        public static string CompressionTitle {
            get {
                return ResourceManager.GetString("CompressionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string EncryptionAlgorithm {
            get {
                return ResourceManager.GetString("EncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key size.
        /// </summary>
        public static string EncryptionKeySize {
            get {
                return ResourceManager.GetString("EncryptionKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption:.
        /// </summary>
        public static string EncryptionTitle {
            get {
                return ResourceManager.GetString("EncryptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password you want to use for encryption..
        /// </summary>
        public static string EnterPasswordDescription {
            get {
                return ResourceManager.GetString("EnterPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPasswordTitle {
            get {
                return ResourceManager.GetString("EnterPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while combining the configured PDF files:.
        /// </summary>
        public static string ErrorCombiningDescription {
            get {
                return ResourceManager.GetString("ErrorCombiningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while combining.
        /// </summary>
        public static string ErrorCombiningTitle {
            get {
                return ResourceManager.GetString("ErrorCombiningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add all PDFs you want to combine. You can re-order them by using drag and drop..
        /// </summary>
        public static string FilesDescription {
            get {
                return ResourceManager.GetString("FilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are files defined that are no valid PDF files. Please remove them and try again..
        /// </summary>
        public static string InvalidFilesExisting {
            get {
                return ResourceManager.GetString("InvalidFilesExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Document Format (*.pdf)|*.pdf.
        /// </summary>
        public static string PdfFilter {
            get {
                return ResourceManager.GetString("PdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF settings.
        /// </summary>
        public static string PdfSettings {
            get {
                return ResourceManager.GetString("PdfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string RibbonGroupActions {
            get {
                return ResourceManager.GetString("RibbonGroupActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string RibbonGroupExtra {
            get {
                return ResourceManager.GetString("RibbonGroupExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        public static string RibbonItemAddFile {
            get {
                return ResourceManager.GetString("RibbonItemAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear files.
        /// </summary>
        public static string RibbonItemClearFiles {
            get {
                return ResourceManager.GetString("RibbonItemClearFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string RibbonItemGenerate {
            get {
                return ResourceManager.GetString("RibbonItemGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove files.
        /// </summary>
        public static string RibbonItemRemoveFile {
            get {
                return ResourceManager.GetString("RibbonItemRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string RibbonItemSettings {
            get {
                return ResourceManager.GetString("RibbonItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string RibbonItemSource {
            get {
                return ResourceManager.GetString("RibbonItemSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party licenses.
        /// </summary>
        public static string RibbonItemThirdPartyLicenses {
            get {
                return ResourceManager.GetString("RibbonItemThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string RibbonTabHome {
            get {
                return ResourceManager.GetString("RibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PDF files ….
        /// </summary>
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target file ….
        /// </summary>
        public static string SelectTargetFile {
            get {
                return ResourceManager.GetString("SelectTargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF files were successfully merged. Do you want to open it in the default program?.
        /// </summary>
        public static string SuccessfullyMergedDescription {
            get {
                return ResourceManager.GetString("SuccessfullyMergedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully merged.
        /// </summary>
        public static string SuccessfullyMergedTitle {
            get {
                return ResourceManager.GetString("SuccessfullyMergedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF combiner.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
