//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfCombiner.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfCombiner.Resources.Language.SettingsResource", typeof(SettingsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string Compression {
            get {
                return ResourceManager.GetString("Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image quality.
        /// </summary>
        public static string CompressionImageQuality {
            get {
                return ResourceManager.GetString("CompressionImageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress images.
        /// </summary>
        public static string CompressionImages {
            get {
                return ResourceManager.GetString("CompressionImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize contents.
        /// </summary>
        public static string CompressionOptimizeContents {
            get {
                return ResourceManager.GetString("CompressionOptimizeContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize fonts.
        /// </summary>
        public static string CompressionOptimizeFonts {
            get {
                return ResourceManager.GetString("CompressionOptimizeFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to contribute.
        /// </summary>
        public static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt documents.
        /// </summary>
        public static string EncryptDocuments {
            get {
                return ResourceManager.GetString("EncryptDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string EncryptionAlgorithm {
            get {
                return ResourceManager.GetString("EncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key size.
        /// </summary>
        public static string EncryptionKeySize {
            get {
                return ResourceManager.GetString("EncryptionKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string GithubRepo {
            get {
                return ResourceManager.GetString("GithubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string GroupGeneral {
            get {
                return ResourceManager.GetString("GroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string GroupInformation {
            get {
                return ResourceManager.GetString("GroupInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idea by.
        /// </summary>
        public static string IdeaBy {
            get {
                return ResourceManager.GetString("IdeaBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required to apply the language change..
        /// </summary>
        public static string LanguageRestartHint {
            get {
                return ResourceManager.GetString("LanguageRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT license.
        /// </summary>
        public static string MitLicense {
            get {
                return ResourceManager.GetString("MitLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize resources.
        /// </summary>
        public static string OptimizeResources {
            get {
                return ResourceManager.GetString("OptimizeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES.
        /// </summary>
        public static string PdfEncryption_Algorithm_AES {
            get {
                return ResourceManager.GetString("PdfEncryption_Algorithm_AES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC4.
        /// </summary>
        public static string PdfEncryption_Algorithm_RC4 {
            get {
                return ResourceManager.GetString("PdfEncryption_Algorithm_RC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128 bit.
        /// </summary>
        public static string PdfEncryption_KeySize_Key128Bit {
            get {
                return ResourceManager.GetString("PdfEncryption_KeySize_Key128Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256 bit.
        /// </summary>
        public static string PdfEncryption_KeySize_Key256Bit {
            get {
                return ResourceManager.GetString("PdfEncryption_KeySize_Key256Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256 bit (revision 6).
        /// </summary>
        public static string PdfEncryption_KeySize_Key256BitRevision6 {
            get {
                return ResourceManager.GetString("PdfEncryption_KeySize_Key256BitRevision6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 bit.
        /// </summary>
        public static string PdfEncryption_KeySize_Key40Bit {
            get {
                return ResourceManager.GetString("PdfEncryption_KeySize_Key40Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under.
        /// </summary>
        public static string ReleasedUnder {
            get {
                return ResourceManager.GetString("ReleasedUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show third party licenses.
        /// </summary>
        public static string ShowThirdPartyLicenses {
            get {
                return ResourceManager.GetString("ShowThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string TabCompression {
            get {
                return ResourceManager.GetString("TabCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TabGeneral {
            get {
                return ResourceManager.GetString("TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string TabSecurity {
            get {
                return ResourceManager.GetString("TabSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
